use customer_behavior;
show databases;
select * from customer limit 5;

## Q1. WHAT IS THE TOTAL REVENUE GENRATED BY MALE V/S FEMALE CUSTOMERS??

select gender, sum(purchase_amount) as revenue
from customer
group by gender;

## Q2. WHICH CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT??

select customer_id,purchase_amount 
from customer
where discount_applied = 'Yes' and 
purchase_amount >= (select AVG (purchase_amount) from customer);

## Q3. WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING??

select item_purchase, round (avg(review_rating),2)
from customer 
group by item_purchased
order by avg(review_rating) desc limit 5;





## Q4. COMPARE THE AVERAGE PURCHASE AMOUNT BETWEEN STANDARD AND EXPRESS SHIPPING??

## Q5. DO SUBSCRIBED CUSTOMER SPEND MORE?? COMPARE AVERAGE SPEND & TOTAL REVENUE BETWEEN SUBSCRIBED AND NON-SUBSCRIBED??

## Q6.  WHICH  5 PRODUCTS HAVE THE HOGHEST PERCENTAGE OF PURCHASES WITH DISCOUNT APPLIED??

## Q7. SEGMENT CUSTOMERS INTO NEW, RETURNING AND LOYAL BASED ON THIER TOTAL NUMEBR OF PREVIOUS PURCHASES AND SHOW THE COUNT OF EACH SEGMENT??

## Q8. WHAT ARE THE TOP3    PURCHASED PRODUCTS WITHIN EACH CATEGORY??

## Q9. ARE CUSTOMERS WHO ARE REPEAT BUYERS (MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE??

## Q10. WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP??




